
output_to_dir: lms-bs-codegen-output
overwrite_if_exists: False
target-project-profile:
  type : java-springboot
  base-dir: C:/Users/91998/ai/gemini/lws
  group-id : com.example
  artifact-id: lws
  save-config:
    - type : ddl
      prefix-path: src/main/resources
    - type : dml
      prefix-path: src/main/resources
    - type: java
      prefix-path: src/main/java

config_files:
  - config\lms-bs\prompt-templates\01-generate-datahub-ddl.yaml
  - config\lms-bs\prompt-templates\02-gen-publisher-openapi-spec.yaml
  - config\lms-bs\prompt-templates\03-gen-books-openapi-spec.yaml
  - config\lms-bs\prompt-templates\04-gen-models-only.yaml
  - config\lms-bs\prompt-templates\05-gen-services-and-repos.yaml
  - config\lms-bs\prompt-templates\06-gen-rest-controllers.yaml
  - config\lms-bs\prompt-templates\07-gen-datahub-dml.yaml
  - config\lms-bs\prompt-templates\08-gen-publisher-api-tests.yaml
  - config\lms-bs\prompt-templates\09-gen-books-api-tests.yaml
  - config\lms-bs\prompt-templates\10-gen-book-search-functionality.yaml
  - config\lms-bs\prompt-templates\10-jquery-gen-book-search-functionality.yaml

 