version : v1
kind : schmea-ddl
metadata:
    name : 09-gen-books-api-tests
    description : "Generate API integration test cases"
    do-not-generate-take-existing-instead : True
spec:
    prompts:
        - text : |
            You are an export JAVA , springboot API tester.
            Given the openapi specficiation, generate the API integration test cases.
            Technical notes:
              - API url is to be taken from enivronment varible API_BASE_URL
              - API url should be in the form of $API_BASE_URL/books

          ctx :
            - output-of: 03-lms-books-openapi-spec