version : v1
kind : openapi-to-springboot-microservices
metadata:
    name : 06-gen-rest-controllers
    description : "Generate java springboot microservices given the openapi spec"
    do-not-generate-take-existing-instead : True
    decorators:
        type : java
        begin-separator: "```java"
        end-separator: "```"
        move-type: BY-PACKAGE
spec:
    prompts:
        - text : |

            You are expert Java, Spring boot 3 microservices developer. 
            You are given a jave repository interfaces, implementations and service classes.

            Generate java class implementation for rest controllers based on services classes provided.
            These classes will have package of com.example.lws.controllers .
            Add error handling and retry mechchanisms for these classes.

            End goal is to develop java, spting boot 3 based micro services with error handling and retry mechanisms.
      
            Follow the package naming as below.
            group is com.example and artifact id is lws
            Entity classes have package of com.example.lws.models .
            Repository interfaces have package of com.example.lws.repository .
            Service classes have package of com.example.lws.services .
            add all imports in the jave files for them to compile.
            
          ctx :
            - output-of: 05-gen-services-and-repos
